server {
    listen       80;
    root    /usr/share/nginx/html;
    server_name  _;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
        location /hosts {
        # 去掉 /api 前缀转发，或者直接透传
        proxy_pass http://backend:8080/hosts;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /hostlist {
        # 去掉 /api 前缀转发，或者直接透传
        proxy_pass http://backend:8080/hostlist;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /items {
        # 去掉 /api 前缀转发，或者直接透传
        proxy_pass http://backend:8080/items;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /post/data {
        # 去掉 /api 前缀转发，或者直接透传
        proxy_pass http://backend:8080/post/data;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /check {
        # 去掉 /api 前缀转发，或者直接透传
        proxy_pass http://backend:8080/check;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
